#define main edax_original_main
#include "../src/all.c"
#undef main
static unsigned rng=0x651197;
static unsigned rr(void){rng^=rng<<13;rng^=rng>>17;return rng^=rng<<5;}
static unsigned long long ref_flip(Board b,int x){
 if((b.player|b.opponent)&(1ULL<<x))return 0;
 unsigned long long ans=0;int r=x/8,c=x%8;
 for(int dr=-1;dr<=1;++dr)for(int dc=-1;dc<=1;++dc)if(dr||dc){int y=r+dr,z=c+dc;unsigned long long run=0;
 while(y>=0&&y<8&&z>=0&&z<8){unsigned long long q=1ULL<<(y*8+z);if(b.opponent&q)run|=q;else{if(b.player&q)ans|=run;break;}y+=dr;z+=dc;}}
 return ans;
}
static unsigned long long ref_moves(Board b){unsigned long long m=0;for(int x=0;x<64;++x)if(ref_flip(b,x))m|=1ULL<<x;return m;}
static Board ref_next(Board b,int x){unsigned long long f=ref_flip(b,x);Board q={b.opponent^f,b.player^f^(1ULL<<x)};return q;}
static int ref_solve(Board b,int alpha,int beta){unsigned long long m=ref_moves(b);if(!m){Board q={b.opponent,b.player};if(ref_moves(q))return -ref_solve(q,-beta,-alpha);int d=bit_count(b.player)-bit_count(b.opponent),e=64-bit_count(b.player|b.opponent);return d>0?d+e:d<0?d-e:0;}int best=-65;while(m){int x=first_bit(m);m&=m-1;int v=-ref_solve(ref_next(b,x),-beta,-alpha);if(v>best)best=v;if(v>alpha)alpha=v;if(alpha>=beta)break;}return best;}
static const char *eval_path(void) { const char *p = getenv("EDAX_EVAL_FILE"); return p ? p : "data/eval.dat"; }
static void init_search(Search *s,int tasks){options.n_task=tasks;options.hash_table_size=10;options.verbosity=0;options.cpu_affinity=false;eval_open(eval_path());search_global_init();search_init(s);}
static Board late_board(int empties){Board b;board_init(&b);while(board_count_empties(&b)>empties){unsigned long long m=ref_moves(b);if(!m){board_pass(&b);m=ref_moves(b);if(!m)break;}int k=rr()%bit_count(m);while(k--)m&=m-1;b=ref_next(b,first_bit(m));}return b;}
static void core(int tasks){Search s;init_search(&s,tasks);unsigned long long checks=0;int exact=0,passes=0;for(int g=0;g<300;++g){Board b;board_init(&b);for(int ply=0;ply<120;++ply){unsigned long long m=ref_moves(b);if(m!=board_get_moves(&b)){puts("FAIL moves");exit(2);}for(int x=0;x<64;++x)if(!((b.player|b.opponent)&(1ULL<<x))){Move mv;unsigned long long f=board_get_move_flip(&b,x,&mv);++checks;if(f!=ref_flip(b,x)){puts("FAIL flips");exit(2);}}
 Board unique;board_unique(&b,&unique);for(int sym=0;sym<8;++sym){Board transformed,u;board_symetry(&b,sym,&transformed);board_unique(&transformed,&u);if(!board_equal(&unique,&u)){puts("FAIL symmetry");exit(2);}}
 if(!m){board_pass(&b);++passes;if(!ref_moves(b))break;continue;}int k=rr()%bit_count(m);while(k--)m&=m-1;int x=first_bit(m);Board next=ref_next(b,x),actual;board_next(&b,x,&actual);if(!board_equal(&next,&actual)){puts("FAIL next");exit(2);}Eval e={0},fresh={0};e.n_empties=board_count_empties(&b);eval_set(&e,&b);eval_update(x,ref_flip(b,x),&e);fresh.n_empties=board_count_empties(&next);eval_set(&fresh,&next);if(memcmp(&e.feature,&fresh.feature,sizeof e.feature)){puts("FAIL incremental eval");exit(2);}b=next;}}
 for(int i=0;i<96;++i){Board b=late_board(1+i%12);int want=ref_solve(b,-65,65);search_cleanup(&s);search_set_board(&s,&b,BLACK);search_set_level(&s,60,board_count_empties(&b));search_run(&s);if(s.result->score!=want){printf("FAIL exact tasks=%d empty=%d expected=%d actual=%d\n",tasks,board_count_empties(&b),want,s.result->score);exit(2);}++exact;}
 printf("PASS core tasks=%d games=300 flip_checks=%llu symmetries=all8 exact_positions=%d empties=1..12 pass_events=%d\n",tasks,checks,exact,passes);search_free(&s);}
int main(int argc,char **argv){if(argc<2)return 1;setbuf(stdout,NULL);bit_init();edge_stability_init();const char *t=argv[1];
 if(!strcmp(t,"bool")){bool b=false;options_read("book-usage","abcdef");printf("value=%d\n",b);}
 else if(!strcmp(t,"short")){Base b;base_init(&b);char *p=malloc(2);p[0]='x';p[1]=0;base_load(&b,p);free(p);base_free(&b);}
 else if(!strcmp(t,"ggf")){Game g;FILE *f=tmpfile();fputs("(;GM[Othello]PB[",f);for(int i=0;i<1000;++i)fputc('a',f);fputs("];)",f);rewind(f);game_import_ggf(&g,f);fclose(f);}
 else if(!strcmp(t,"edx")){Game g;Base b,c;remove("audit-roundtrip.edx");game_init(&g);g.move[0]=26;g.date.month=10;base_init(&b);base_init(&c);base_append(&b,&g);base_save(&b,"audit-roundtrip.edx");base_load(&c,"audit-roundtrip.edx");printf("EDX roundtrip expected_games=1 actual=%d expected_firstmove=26 actual=%d\n",c.n_games,c.n_games?c.game[0].move[0]:-1);if(c.n_games!=1||c.game[0].move[0]!=26)return 2;base_free(&b);base_free(&c);}
 else if(!strcmp(t,"savefail")){Book b={0};book_init(&b);int ok=book_save(&b,"audit-directory-does-not-exist/book.dat");book_free(&b);printf("BOOK save to missing directory accepted=%d\n",ok);if(ok)return 2;}
 else if(!strcmp(t,"analyze")){Search s;init_search(&s,1);Game g;game_init(&g);g.initial_board=late_board(4);printf("ANALYZE custom initial empty=%d moves=0\n",board_count_empties(&g.initial_board));fflush(stdout);game_analyze(&g,&s,4,false);search_free(&s);}
 else if(!strcmp(t,"enhance")){Search s;init_search(&s,1);Book b={0};b.search=&s;book_init(&b);b.options.level=0;b.options.n_empties=58;options.book_file="audit-enhance.dat";Board start;board_init(&start);book_add_board(&b,&start);book_enhance(&b,&start,64,64);printf("ENHANCE nodes_after=%d\n",b.n_nodes);book_clean(&b);position_negamax(book_probe(&b,&start),&b);book_clean(&b);position_enhance(book_probe(&b,&start),&b);int pending=0;Position *p;PositionArray *a;Book *bp=&b;foreach_position(p,a,bp)pending+=p->todo;printf("ENHANCE pending_after_finished=%d\n",pending);book_free(&b);search_free(&s);}
 else if(!strcmp(t,"core")){core(argc>2?atoi(argv[2]):1);}
 else if(!strcmp(t,"nboard")){Result result={0};result.n_nodes=1234;result.time=12345;nboard_observer(&result);}
 else if(!strcmp(t,"gtp")||!strcmp(t,"gtptime")||!strcmp(t,"gtpreg")||!strcmp(t,"xboard")){
 options.n_task=1;options.hash_table_size=10;options.verbosity=0;options.cpu_affinity=false;options.book_file="tests/merge-complete-fixture.dat";
 eval_open(eval_path());search_global_init();UI *ui=mm_malloc(sizeof *ui);memset(ui,0,sizeof *ui);event_init(&ui->event);
 if(!strcmp(t,"xboard")){ui->type=UI_XBOARD;ui_init_xboard(ui);event_add_message(&ui->event,string_duplicate("level 0 5 1"));event_add_message(&ui->event,string_duplicate("quit"));ui_loop_xboard(ui);ui_free_xboard(ui);}
 else {ui->type=UI_GTP;ui_init_gtp(ui);if(!strcmp(t,"gtp")){event_add_message(&ui->event,string_duplicate("42 play white d3"));event_add_message(&ui->event,string_duplicate("7 name"));event_add_message(&ui->event,string_duplicate("name"));}
 else if(!strcmp(t,"gtpreg")){options.level=0;event_add_message(&ui->event,string_duplicate("reg_genmove black"));} else{ui->play->force.real[0].opponent=0x12345678;printf("GTP before forced_board=%llx\n",ui->play->force.real[0].opponent);event_add_message(&ui->event,string_duplicate("time_left banana 99 0"));}
 event_add_message(&ui->event,string_duplicate("quit"));ui_loop_gtp(ui);if(!strcmp(t,"gtptime"))printf("GTP after forced_board=%llx\n",ui->play->force.real[0].opponent);ui_free_gtp(ui);}
 event_free(&ui->event);mm_free(ui);
 }
 else if(!strcmp(t,"formats")){Game src,dst;Random random;random_seed(&random,1234);game_rand(&src,20,&random);src.date.year=2026;src.date.month=9;src.date.day=27;src.date.hour=1;src.date.minute=2;src.date.second=3;
 void (*exports[4])(const Game*,FILE*)={game_export_text,game_export_ggf,game_export_sgf,game_export_pgn};void (*imports[4])(Game*,FILE*)={game_import_text,game_import_ggf,game_import_sgf,game_import_pgn};const char *names[]={"txt","ggf","sgf","pgn"};
 for(int j=0;j<4;++j){FILE *f=tmpfile();exports[j](&src,f);rewind(f);imports[j](&dst,f);printf("FORMAT %s board_equal=%d moves_equal=%d date=%d/%d/%d %d:%d:%d\n",names[j],board_equal(&src.initial_board,&dst.initial_board),memcmp(src.move,dst.move,60)==0,dst.date.year,dst.date.month,dst.date.day,dst.date.hour,dst.date.minute,dst.date.second);fclose(f);}
 game_init(&src);src.initial_board=late_board(4);FILE *f=tmpfile();game_export_pgn(&src,f);rewind(f);game_import_pgn(&dst,f);printf("PGN_CUSTOM expected_empty=%d actual_empty=%d board_equal=%d\n",board_count_empties(&src.initial_board),board_count_empties(&dst.initial_board),board_equal(&src.initial_board,&dst.initial_board));fclose(f);
 }
 else if(!strcmp(t,"pgnlong")){Game g;FILE *f=tmpfile();fputs("[Event \"audit\"]\n",f);for(int i=0;i<300;++i)fprintf(f,"%d. d3 c3 ",i+1);rewind(f);game_import_pgn(&g,f);fclose(f);}
 else if(!strcmp(t,"pgnfen")){Game g;Board want=late_board(12);char fen[128];FILE *f=tmpfile();fprintf(f,"[FEN \"%s\"]\n*\n",board_to_FEN(&want,BLACK,fen));rewind(f);game_import_pgn(&g,f);printf("PGN FEN expected_empty=%d actual_empty=%d\n",board_count_empties(&want),board_count_empties(&g.initial_board));fclose(f);}
 else if(!strcmp(t,"unsupported")){FILE *f=fopen("audit-sentinel.xyz","wb");fputs("KEEP THIS FILE",f);fclose(f);Play *p=mm_malloc(sizeof *p);memset(p,0,sizeof *p);board_init(&p->initial_board);p->initial_player=BLACK;play_save(p,"audit-sentinel.xyz");f=fopen("audit-sentinel.xyz","rb");fseek(f,0,SEEK_END);printf("UNSUPPORTED SAVE bytes_before=14 bytes_after=%ld\n",ftell(f));fclose(f);mm_free(p);}
 else if(!strcmp(t,"bookio")){Book b={0},c={0};FILE *f=fopen("audit-book-saved.dat","wb");fputs("KEEP",f);fclose(f);if(!book_load(&b,"tests/merge-complete-fixture.dat")||b.n_nodes!=2)return 2;if(!book_save(&b,"audit-book-saved.dat"))return 2;if(!book_load(&c,"audit-book-saved.dat")||c.n_nodes!=2)return 2;printf("BOOK save and reload nodes=%d\n",c.n_nodes);book_free(&b);book_free(&c);}
 else if(!strcmp(t,"truncated")){FILE *in=fopen("tests/merge-complete-fixture.dat","rb"),*out=fopen("audit-truncated.dat","wb");fseek(in,0,SEEK_END);long n=ftell(in);rewind(in);for(long i=0;i<n-1;++i)fputc(fgetc(in),out);fclose(in);fclose(out);Book b={0};int ok=book_load(&b,"audit-truncated.dat");printf("TRUNCATED accepted=%d nodes=%d original_expected=2\n",ok,b.n_nodes);book_free(&b);if(ok)return 2;}
 else if(!strcmp(t,"corruptstartup")){FILE *in=fopen("tests/merge-complete-fixture.dat","rb"),*out=fopen("audit-truncated.dat","wb");fseek(in,0,SEEK_END);long n=ftell(in);rewind(in);for(long i=0;i<n-1;++i)fputc(fgetc(in),out);fclose(in);fclose(out);options.n_task=1;options.hash_table_size=10;options.verbosity=0;options.cpu_affinity=false;options.book_file="audit-truncated.dat";eval_open(eval_path());search_global_init();UI *ui=mm_malloc(sizeof *ui);memset(ui,0,sizeof *ui);event_init(&ui->event);ui->type=UI_GTP;ui_init_gtp(ui);int safe=!ui->book.need_saving;ui_free_gtp(ui);event_free(&ui->event);mm_free(ui);in=fopen("audit-truncated.dat","rb");fseek(in,0,SEEK_END);long after=ftell(in);fclose(in);printf("CORRUPT STARTUP autosave_disabled=%d original_bytes=%ld after_bytes=%ld\n",safe,n-1,after);if(!safe||after!=n-1)return 2;}
 else if(!strcmp(t,"ggsclock")){GGSClock c;char input[WORD_SIZE+1];memset(input,'1',WORD_SIZE);input[WORD_SIZE]=0;ggs_parse_clock(&c,input);}
 else if(!strcmp(t,"cassio")){options.n_task=1;options.hash_table_size=10;options.verbosity=0;options.cpu_affinity=false;eval_open(eval_path());search_global_init();Engine *e=calloc(1,sizeof *e);e->search=engine_create_search();for(int i=0;i<24;++i){Board b=late_board(3+i%7);char text[80];int want=ref_solve(b,-65,65);for(int repeat=0;repeat<2;++repeat){int got=engine_endgame_search(e,board_to_string(&b,BLACK,text),-64,64,100);if(got!=want){printf("FAIL Cassio expected=%d actual=%d\n",want,got);return 2;}}}engine_free(e->search);free(e);puts("PASS Cassio endgame API 24 positions x 2 repeated searches");}
 else if(!strcmp(t,"events")){Event ev;event_init(&ev);int expected=0;for(int i=0;i<10000;++i){char b[32];sprintf(b,"%d",i);event_add_message(&ev,string_duplicate(b));if(i%3==0){char *s=event_peek_message(&ev);if(!s||atoi(s)!=expected++)return 2;free(s);}}char *s;while((s=event_peek_message(&ev))){if(atoi(s)!=expected++)return 2;free(s);}printf("PASS event FIFO %d messages with wrap and growth\n",expected);event_free(&ev);}
 else return 1;
 return 0;
}
